package com.vision.testmicroservice.model.type;

public enum ERole {
    ROLE_ADMIN,
    ROLE_SOURCING_CLIENT,
    ROLE_TRADING_CLIENT,
    ROLE_ASSOCIATE_QUALITY_CONTROL,
    ROLE_SAMPLE_COORDINATOR,
    ROLE_QUALITY_CONTROL,
    ROLE_HEAD_MERCHANDISER,
    ROLE_MERCHANDISER,
    ROLE_FACTORY,
    ROLE_CLIENT,
    ROLE_DISPATCH_COORDINATOR
}
